'use client'

import { useCallback } from "react";

export const getMermaidConfig = useCallback((isDark: boolean) => {
    const baseConfig = {
      startOnLoad: false,
      securityLevel: 'loose',
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
      fontSize: 14,
      darkMode: isDark,
      theme: isDark ? 'dark' : 'base',
    };

    // Enhanced theme variables for better contrast and readability
    const themeVariables = isDark ? {
      // Dark theme variables
      primaryColor: '#3b82f6',
      primaryTextColor: '#f8fafc',
      primaryBorderColor: '#1e40af',
      lineColor: '#64748b',
      sectionBkgColor: '#1e293b',
      altSectionBkgColor: '#334155',
      gridColor: '#475569',
      secondaryColor: '#64748b',
      tertiaryColor: '#475569',
      background: '#0f172a',
      mainBkg: '#1e293b',
      secondBkg: '#334155',
      tertiaryBkg: '#475569',
      primaryBkgColor: '#3b82f6',
      textColor: '#f1f5f9',
      nodeBorder: '#64748b',
      clusterBkg: '#334155',
      clusterBorder: '#64748b',
      defaultLinkColor: '#64748b',
      titleColor: '#f1f5f9',
      edgeLabelBackground: '#1e293b',
      nodeTextColor: '#f1f5f9',
      // Flowchart specific
      flowchartNodeBkg: '#334155',
      flowchartNodeBorder: '#64748b',
      flowchartEdgeColor: '#64748b',
      flowchartLinkColor: '#64748b',
      // Sequence diagram specific
      actorBkg: '#334155',
      actorBorder: '#64748b',
      actorTextColor: '#f1f5f9',
      actorLineColor: '#64748b',
      signalColor: '#64748b',
      signalTextColor: '#f1f5f9',
      labelBoxBkgColor: '#1e293b',
      labelBoxBorderColor: '#64748b',
      labelTextColor: '#f1f5f9',
      loopTextColor: '#f1f5f9',
      noteBorderColor: '#64748b',
      noteBkgColor: '#1e293b',
      noteTextColor: '#f1f5f9',
      // Gantt specific
      ganttTaskBkgColor: '#334155',
      ganttTaskTextColor: '#f1f5f9',
      ganttActiveTaskBkgColor: '#3b82f6',
      ganttActiveTaskBorderColor: '#1e40af',
      ganttGridColor: '#475569',
      ganttSectionBkgColor: '#1e293b',
      ganttTodayLineColor: '#ef4444',
      // Git specific
      git0: '#3b82f6',
      git1: '#10b981',
      git2: '#f59e0b',
      git3: '#ef4444',
      git4: '#8b5cf6',
      git5: '#06b6d4',
      git6: '#84cc16',
      git7: '#f97316',
      // Class diagram specific
      classText: '#f1f5f9',
      classBkg: '#334155',
      classBorder: '#64748b',
      relationColor: '#64748b',
      relationLabelColor: '#f1f5f9',
      relationLabelBkg: '#1e293b',
      // State diagram specific
      stateBkg: '#334155',
      stateBorder: '#64748b',
      stateText: '#f1f5f9',
      transitionColor: '#64748b',
      transitionLabelColor: '#f1f5f9',
      // Journey specific
      fillType0: '#3b82f6',
      fillType1: '#10b981',
      fillType2: '#f59e0b',
      fillType3: '#ef4444',
      fillType4: '#8b5cf6',
      fillType5: '#06b6d4',
      fillType6: '#84cc16',
      fillType7: '#f97316',
    } : {
      // Light theme variables
      primaryColor: '#3b82f6',
      primaryTextColor: '#1e293b',
      primaryBorderColor: '#2563eb',
      lineColor: '#64748b',
      sectionBkgColor: '#f8fafc',
      altSectionBkgColor: '#f1f5f9',
      gridColor: '#e2e8f0',
      secondaryColor: '#64748b',
      tertiaryColor: '#94a3b8',
      background: '#ffffff',
      mainBkg: '#ffffff',
      secondBkg: '#f8fafc',
      tertiaryBkg: '#f1f5f9',
      primaryBkgColor: '#3b82f6',
      textColor: '#1e293b',
      nodeBorder: '#e2e8f0',
      clusterBkg: '#f8fafc',
      clusterBorder: '#e2e8f0',
      defaultLinkColor: '#64748b',
      titleColor: '#1e293b',
      edgeLabelBackground: '#ffffff',
      nodeTextColor: '#1e293b',
      // Flowchart specific
      flowchartNodeBkg: '#ffffff',
      flowchartNodeBorder: '#e2e8f0',
      flowchartEdgeColor: '#64748b',
      flowchartLinkColor: '#64748b',
      // Sequence diagram specific
      actorBkg: '#ffffff',
      actorBorder: '#e2e8f0',
      actorTextColor: '#1e293b',
      actorLineColor: '#e2e8f0',
      signalColor: '#64748b',
      signalTextColor: '#1e293b',
      labelBoxBkgColor: '#f8fafc',
      labelBoxBorderColor: '#e2e8f0',
      labelTextColor: '#1e293b',
      loopTextColor: '#1e293b',
      noteBorderColor: '#e2e8f0',
      noteBkgColor: '#fefce8',
      noteTextColor: '#1e293b',
      // Gantt specific
      ganttTaskBkgColor: '#f8fafc',
      ganttTaskTextColor: '#1e293b',
      ganttActiveTaskBkgColor: '#3b82f6',
      ganttActiveTaskBorderColor: '#2563eb',
      ganttGridColor: '#e2e8f0',
      ganttSectionBkgColor: '#ffffff',
      ganttTodayLineColor: '#ef4444',
      // Git specific
      git0: '#3b82f6',
      git1: '#10b981',
      git2: '#f59e0b',
      git3: '#ef4444',
      git4: '#8b5cf6',
      git5: '#06b6d4',
      git6: '#84cc16',
      git7: '#f97316',
      // Class diagram specific
      classText: '#1e293b',
      classBkg: '#ffffff',
      classBorder: '#e2e8f0',
      relationColor: '#64748b',
      relationLabelColor: '#1e293b',
      relationLabelBkg: '#ffffff',
      // State diagram specific
      stateBkg: '#ffffff',
      stateBorder: '#e2e8f0',
      stateText: '#1e293b',
      transitionColor: '#64748b',
      transitionLabelColor: '#1e293b',
      // Journey specific
      fillType0: '#3b82f6',
      fillType1: '#10b981',
      fillType2: '#f59e0b',
      fillType3: '#ef4444',
      fillType4: '#8b5cf6',
      fillType5: '#06b6d4',
      fillType6: '#84cc16',
      fillType7: '#f97316',
    };

    return {
      ...baseConfig,
      themeVariables,
      flowchart: {
        curve: 'basis',
        htmlLabels: true,
        nodeSpacing: 50,
        rankSpacing: 50,
        padding: 10,
        useMaxWidth: true,
      },
      sequence: {
        diagramMarginX: 50,
        diagramMarginY: 10,
        actorMargin: 50,
        width: 150,
        height: 65,
        boxMargin: 10,
        boxTextMargin: 5,
        noteMargin: 10,
        messageMargin: 35,
        messageAlign: 'center',
        mirrorActors: true,
        bottomMarginAdj: 1,
        useMaxWidth: true,
      },
      gantt: {
        titleTopMargin: 25,
        barHeight: 20,
        fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
        fontSize: 12,
        fontWeight: 'normal',
        gridLineStartPadding: 35,
        bottomPadding: 25,
        rightPadding: 75,
        leftPadding: 75,
        topPadding: 50,
        topAxis: false,
        axisFormat: '%m/%d/%Y',
        tickInterval: '1day',
        useMaxWidth: true,
      },
      c4: {
        diagramMarginX: 50,
        diagramMarginY: 10,
        c4ShapeMargin: 50,
        c4ShapePadding: 20,
        width: 216,
        height: 60,
        boxMargin: 10,
        useMaxWidth: true,
      },
      gitGraph: {
        diagramPadding: 8,
        nodeLabel: {
          width: 75,
          height: 100,
          x: -25,
          y: 0,
        },
        mainBranchName: 'main',
        showCommitLabel: true,
        showBranches: true,
        rotateCommitLabel: true,
        useMaxWidth: true,
      },
      journey: {
        diagramMarginX: 50,
        diagramMarginY: 10,
        leftMargin: 150,
        width: 150,
        height: 50,
        boxMargin: 10,
        boxTextMargin: 5,
        noteMargin: 10,
        messageMargin: 35,
        messageAlign: 'center',
        bottomMarginAdj: 1,
        useMaxWidth: true,
      },
      class: {
        titleTopMargin: 25,
        useMaxWidth: true,
      },
      state: {
        titleTopMargin: 25,
        useMaxWidth: true,
      },
      er: {
        diagramPadding: 20,
        layoutDirection: 'TB',
        minEntityWidth: 100,
        minEntityHeight: 75,
        entityPadding: 15,
        stroke: isDark ? '#64748b' : '#e2e8f0',
        fill: isDark ? '#334155' : '#ffffff',
        fontSize: 12,
        useMaxWidth: true,
      },
      pie: {
        textPosition: 0.75,
        useMaxWidth: true,
      },
      requirement: {
        rect_fill: isDark ? '#334155' : '#ffffff',
        text_color: isDark ? '#f1f5f9' : '#1e293b',
        rect_border_size: '0.5px',
        rect_border_color: isDark ? '#64748b' : '#e2e8f0',
        rect_min_width: 200,
        rect_min_height: 200,
        fontSize: 14,
        rect_padding: 10,
        line_height: 20,
        useMaxWidth: true,
      },
    };
  }, []);



  